language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm install
  - npm install -g concurrently
  - cd server && npm install
  - cd ../client && npm install
  - npm run dev
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branches:
      only:
        - master
        - instabaddAttempt2