language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
services:
  -mongodb
script:
  - npm install
  - npm install -g concurrently
  - cd client && npm install
  - cd ../server && npm install
  - npm run dev
deploy:
  provider: pages
  skip_cleanup: true
  MONGODB_URL: $MONGODB_URL
  github_token: $github_token
  local_dir: build
  on:
    branches:
      only:
        - master
        - instabaddAttempt2